### ISSUE TITLE
Add consumer proguard in library

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/EasyGlide#10]
Get proguard config from [Glide](https://github.com/bumptech/glide) and put in consumer proguard in EasyGlide library. 

It will help who implements this library avoiding to touch proguard's in app module to use glide specific rules.

**Comment by gemasr** [comment]
Can I help with this one?

**Comment by pedrofsn** [comment]
YEAH @gemasr! :)

**Comment by pedrofsn** [comment]
Thanks @gemasr!!

**Comment by pedrofsn** [comment]
I've other repositories with the same need, @gemasr. It'll be nice if you can collaborate with this repositories too. :)

- https://github.com/pedrofsn/data-form/issues/12
- https://github.com/pedrofsn/EasyRecyclerview/issues/6
- https://github.com/pedrofsn/base-redcode/issues/15
