### ISSUE TITLE
Programmatically placeholder

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/EasyGlide#2]
Today placehoder is hardcoded as 

> private const val placeholder = android.R.drawable.stat_sys_download

In [ExtensionImageView.kt:32](https://github.com/pedrofsn/EasyGlide/blob/master/easy-glide/src/main/java/br/com/redcode/easyglide/library/ExtensionImageView.kt#L32)
____
- This issue is a improvement to handle placeholder programmatically to who implements the library;
- Drawable "android.R.drawable.stat_sys_download" can be used as DEFAULT value;
- Need to handle/accept null case ("without any placeholder").

**Comment by sierraobryan** [comment]
I'll work on this and #5 for you

**Comment by pedrofsn** [comment]
Thanks @sierraobryan !

**Comment by sierraobryan** [comment]
Easiest is just to make a `imageView.loadWithPlaceholder( ... )` function, is that what you're looking for? Or are you looking for glide-esque `image.load().placeholder`? Or built off your current implementation or `imageView.load(url, withPlaceholder: Boolean? = false, placeholderResId: Int? = null)`?

**Comment by sierraobryan** [comment]
@pedrofsn is this set up so you can push? I've tried everything on my end to contribute.

**Comment by sierraobryan** [comment]
https://github.com/pedrofsn/EasyGlide/pull/6

**Comment by pedrofsn** [comment]
Thanks @sierraobryan
