### ISSUE TITLE
Programmatically error

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/EasyGlide#3]
Today error drawable is hardcoded as 

> private val error = R.drawable.ic_error

In [ExtensionImageView.kt:33](https://github.com/pedrofsn/EasyGlide/blob/master/easy-glide/src/main/java/br/com/redcode/easyglide/library/ExtensionImageView.kt#L33)
____
- This issue is a improvement to handle drawable error programmatically to who implements the library;
- Drawable "R.drawable.ic_error" can be used as DEFAULT value;
- Need to handle/accept null case ("without any error drawable").

**Comment by sierraobryan** [comment]
#9

**Comment by pedrofsn** [comment]
Thanks @sierraobryan
