### ISSUE TITLE
Handle drawable error in databinding

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/EasyGlide#4]
After issue #3 be closed, handle this in [EasyGlideBindingAdapters.kt](https://github.com/pedrofsn/EasyGlide/blob/master/easy-glide-databinding/src/main/java/br/com/redcode/easyglide/databinding/library/EasyGlideBindingAdapters.kt)

**Comment by sierraobryan** [comment]
#8

**Comment by pedrofsn** [comment]
Thanks @sierraobryan
