### ISSUE TITLE
Handle drawable placeholder in databinding

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/EasyGlide#5]
After issue #2 be closed, handle this in [EasyGlideBindingAdapters.kt](https://github.com/pedrofsn/EasyGlide/blob/master/easy-glide-databinding/src/main/java/br/com/redcode/easyglide/databinding/library/EasyGlideBindingAdapters.kt)

**Comment by sierraobryan** [comment]
#7

**Comment by pedrofsn** [comment]
Thanks @sierraobryan
